export const IS_FIRST_TIME = 'IS_FIRST_TIME';
export const PASSWORD_VALID_TILL = 'PASSWORD_VALID_TILL';
export const IS_LOCKED = 'IS_LOCKED';
export const ACCOUNT_STORAGE_KEY = 'NEXORE';

export const PBKDF2_ITERATIONS = 600_000;
