export const NOT_HAS_CIPHER = 'NOT_HAS_CIPHER';
export const PASSWORD_VALID_TILL = 'PASSWORD_VALID_TILL';
export const IS_LOCKED = 'IS_LOCKED';
export const KEYRING_STORE = 'KEYRING_STORE';
export const PRIVATE_KEYRING_STORE = 'PRIVATE_KEYRING_STORE';
export const ACCOUNT_METADATA = 'ACCOUNT_METADATA';
export const CURRENT_ACCOUNT_METADATA = 'CURRENT_ACCOUNT_METADATA';

export const DEFAULT_LOCK = 600_000;
export const PBKDF2_ITERATIONS = 600_000;
